spring.application.name=erp-backend

# Sunucu Portu
server.port=8080

# PostgreSQL Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/nexom_erp_db
spring.datasource.username=postgres
spring.datasource.password=root123

# Hibernate (JPA) Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Dosya Yükleme (Multipart) Ayarları
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
