spring.application.name=erp-backend

# Sunucu Portu
server.port=8080

# H2 Bellek Veritabanı Ayarları
spring.datasource.url=jdbc:h2:mem:nexom_erp_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (JPA) Otomatik Tablo Oluşturma Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Web Konsolu (Tarayıcıdan Veritabanını Görmek İçin)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
